---
driver:
  name: vagrant

verifier:
  name: inspec

provisioner:
  name: chef_zero
  attributes:
    apt:
      compile_time_update: true
      confd:
        install_recommends: false

platforms:
  - name: centos-6.8
  - name: centos-7.2
  - name: ubuntu-14.04
    run_list:
      - recipe[apt::default]
  - name: ubuntu-16.04
    run_list:
      - recipe[apt::default]
  - name: debian-8.5
    run_list:
      - recipe[apt::default]

suites:
  - name: chef12
    driver:
      require_chef_omnibus: 12.21.4
    verifier:
      inspec_tests:
        - test/smoke/default
    run_list:
      - recipe[icinga2repo::default]
      - recipe[icinga2repo_test::default]

  - name: chef13
    driver:
      require_chef_omnibus: 13.3.42
    verifier:
      inspec_tests:
        - test/smoke/default
    run_list:
      - recipe[icinga2repo::default]
      - recipe[icinga2repo_test::default]
